ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create dedicated Debezium user
CREATE USER c##dbezium IDENTIFIED BY dbezium123 CONTAINER=ALL;
GRANT CONNECT TO c##dbezium CONTAINER=ALL;
GRANT CREATE SESSION TO c##dbezium CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO c##dbezium CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbezium CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbezium CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbezium CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbezium CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbezium CONTAINER=ALL;
GRANT LOGMINING TO c##dbezium CONTAINER=ALL;
GRANT CREATE TABLE TO c##dbezium CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbezium CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbezium CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO c##dbezium CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbezium CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbezium CONTAINER=ALL;
GRANT UNLIMITED TABLESPACE TO c##dbezium CONTAINER=ALL;

-- Alter session to FREEPDB1
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create user
CREATE USER app IDENTIFIED BY apppass;
GRANT CONNECT, RESOURCE TO app;
GRANT CREATE SESSION TO app;
GRANT UNLIMITED TABLESPACE TO app;

-- Grant permissions for CDC (LogMiner)
GRANT SELECT ANY TRANSACTION TO app;
GRANT FLASHBACK ANY TABLE TO app;
GRANT SELECT ANY TABLE TO app;
GRANT LOCK ANY TABLE TO app;
GRANT CREATE TABLE TO app;
GRANT ALTER ANY TABLE TO app;
GRANT SELECT_CATALOG_ROLE TO app;
GRANT EXECUTE_CATALOG_ROLE TO app;
GRANT SELECT ANY DICTIONARY TO app;
GRANT LOGMINING TO app;


-- Enable supplemental logging (required for Debezium)
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Connect as orderuser and create table
-- The application will create the table automatically, but you can create it manually:

CREATE TABLE app.users (
  id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name    VARCHAR2(100),
  email   VARCHAR2(200),
  updated TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE PUBLIC SYNONYM users 
FOR app.users;

-- Enable supplemental logging for the orders table (REQUIRED for Debezium CDC)
ALTER TABLE app.users ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
