// Code generated by 'yaegi extract github.com/litesql/go-ha'. DO NOT EDIT.

package interceptor

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"github.com/litesql/go-ha"
	"go/constant"
	"go/token"
	"io"
	"reflect"
)

func init() {
	Symbols["github.com/litesql/go-ha/ha"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CrossShardQuery":                reflect.ValueOf(ha.CrossShardQuery),
		"DefaultStream":                  reflect.ValueOf(constant.MakeFromLiteral("\"ha_replication\"", token.STRING, 0)),
		"ErrInvalidSQL":                  reflect.ValueOf(&ha.ErrInvalidSQL).Elem(),
		"ErrSnapshotterNotConfigured":    reflect.ValueOf(&ha.ErrSnapshotterNotConfigured).Elem(),
		"Full":                           reflect.ValueOf(ha.Full),
		"LatestSnapshot":                 reflect.ValueOf(ha.LatestSnapshot),
		"ListDSN":                        reflect.ValueOf(ha.ListDSN),
		"ListReplicationIDs":             reflect.ValueOf(ha.ListReplicationIDs),
		"LookupConnector":                reflect.ValueOf(ha.LookupConnector),
		"LookupConnectorByReplicationID": reflect.ValueOf(ha.LookupConnectorByReplicationID),
		"NameToOptions":                  reflect.ValueOf(ha.NameToOptions),
		"NewAsyncNATSPublisher":          reflect.ValueOf(ha.NewAsyncNATSPublisher),
		"NewChangeSet":                   reflect.ValueOf(ha.NewChangeSet),
		"NewConnector":                   reflect.ValueOf(ha.NewConnector),
		"NewJSONPublisher":               reflect.ValueOf(ha.NewJSONPublisher),
		"NewNATSPublisher":               reflect.ValueOf(ha.NewNATSPublisher),
		"NewNATSSnapshotter":             reflect.ValueOf(ha.NewNATSSnapshotter),
		"NewNATSSubscriber":              reflect.ValueOf(ha.NewNATSSubscriber),
		"NewNoopPublisher":               reflect.ValueOf(ha.NewNoopPublisher),
		"NewNoopSnapshotter":             reflect.ValueOf(ha.NewNoopSnapshotter),
		"NewNoopSubscriber":              reflect.ValueOf(ha.NewNoopSubscriber),
		"NewWriterPublisher":             reflect.ValueOf(ha.NewWriterPublisher),
		"PK":                             reflect.ValueOf(ha.PK),
		"Parse":                          reflect.ValueOf(ha.Parse),
		"ParseStatement":                 reflect.ValueOf(ha.ParseStatement),
		"Rowid":                          reflect.ValueOf(ha.Rowid),
		"Shutdown":                       reflect.ValueOf(ha.Shutdown),
		"TXCookieName":                   reflect.ValueOf(constant.MakeFromLiteral("\"_txseq\"", token.STRING, 0)),
		"TypeAlterTable":                 reflect.ValueOf(constant.MakeFromLiteral("\"ALTER TABLE\"", token.STRING, 0)),
		"TypeAnalyze":                    reflect.ValueOf(constant.MakeFromLiteral("\"ANALYZE\"", token.STRING, 0)),
		"TypeBegin":                      reflect.ValueOf(constant.MakeFromLiteral("\"BEGIN\"", token.STRING, 0)),
		"TypeCommit":                     reflect.ValueOf(constant.MakeFromLiteral("\"COMMIT\"", token.STRING, 0)),
		"TypeCreateIndex":                reflect.ValueOf(constant.MakeFromLiteral("\"CREATE INDEX\"", token.STRING, 0)),
		"TypeCreateTable":                reflect.ValueOf(constant.MakeFromLiteral("\"CREATE TABLE\"", token.STRING, 0)),
		"TypeCreateTrigger":              reflect.ValueOf(constant.MakeFromLiteral("\"CREATE TRIGGER\"", token.STRING, 0)),
		"TypeCreateView":                 reflect.ValueOf(constant.MakeFromLiteral("\"CREATE VIEW\"", token.STRING, 0)),
		"TypeCreateVirtualTable":         reflect.ValueOf(constant.MakeFromLiteral("\"CREATE VIRTUAL TABLE\"", token.STRING, 0)),
		"TypeDelete":                     reflect.ValueOf(constant.MakeFromLiteral("\"DELETE\"", token.STRING, 0)),
		"TypeDrop":                       reflect.ValueOf(constant.MakeFromLiteral("\"DROP\"", token.STRING, 0)),
		"TypeExplain":                    reflect.ValueOf(constant.MakeFromLiteral("\"EXPLAIN\"", token.STRING, 0)),
		"TypeInsert":                     reflect.ValueOf(constant.MakeFromLiteral("\"INSERT\"", token.STRING, 0)),
		"TypeOther":                      reflect.ValueOf(constant.MakeFromLiteral("\"OTHER\"", token.STRING, 0)),
		"TypePragma":                     reflect.ValueOf(constant.MakeFromLiteral("\"PRAGMA\"", token.STRING, 0)),
		"TypeRelease":                    reflect.ValueOf(constant.MakeFromLiteral("\"RELEASE\"", token.STRING, 0)),
		"TypeRollback":                   reflect.ValueOf(constant.MakeFromLiteral("\"ROLLBACK\"", token.STRING, 0)),
		"TypeSavepoint":                  reflect.ValueOf(constant.MakeFromLiteral("\"SAVEPOINT\"", token.STRING, 0)),
		"TypeSelect":                     reflect.ValueOf(constant.MakeFromLiteral("\"SELECT\"", token.STRING, 0)),
		"TypeUpdate":                     reflect.ValueOf(constant.MakeFromLiteral("\"UPDATE\"", token.STRING, 0)),
		"TypeVacuum":                     reflect.ValueOf(constant.MakeFromLiteral("\"VACUUM\"", token.STRING, 0)),
		"UnverifiedStatement":            reflect.ValueOf(ha.UnverifiedStatement),
		"WithAsyncPublisher":             reflect.ValueOf(ha.WithAsyncPublisher),
		"WithAsyncPublisherOutboxDir":    reflect.ValueOf(ha.WithAsyncPublisherOutboxDir),
		"WithAutoStart":                  reflect.ValueOf(ha.WithAutoStart),
		"WithCDCPublisher":               reflect.ValueOf(ha.WithCDCPublisher),
		"WithChangeSetInterceptor":       reflect.ValueOf(ha.WithChangeSetInterceptor),
		"WithClusterSize":                reflect.ValueOf(ha.WithClusterSize),
		"WithDBSnapshotter":              reflect.ValueOf(ha.WithDBSnapshotter),
		"WithDeliverPolicy":              reflect.ValueOf(ha.WithDeliverPolicy),
		"WithDisableDDLSync":             reflect.ValueOf(ha.WithDisableDDLSync),
		"WithEmbeddedNatsConfig":         reflect.ValueOf(ha.WithEmbeddedNatsConfig),
		"WithExtensions":                 reflect.ValueOf(ha.WithExtensions),
		"WithGrpcPort":                   reflect.ValueOf(ha.WithGrpcPort),
		"WithGrpcTimeout":                reflect.ValueOf(ha.WithGrpcTimeout),
		"WithLeaderElectionLocalTarget":  reflect.ValueOf(ha.WithLeaderElectionLocalTarget),
		"WithLeaderProvider":             reflect.ValueOf(ha.WithLeaderProvider),
		"WithName":                       reflect.ValueOf(ha.WithName),
		"WithNatsOptions":                reflect.ValueOf(ha.WithNatsOptions),
		"WithPublisherTimeout":           reflect.ValueOf(ha.WithPublisherTimeout),
		"WithQueryRouter":                reflect.ValueOf(ha.WithQueryRouter),
		"WithReplicas":                   reflect.ValueOf(ha.WithReplicas),
		"WithReplicationID":              reflect.ValueOf(ha.WithReplicationID),
		"WithReplicationPublisher":       reflect.ValueOf(ha.WithReplicationPublisher),
		"WithReplicationStream":          reflect.ValueOf(ha.WithReplicationStream),
		"WithReplicationSubscriber":      reflect.ValueOf(ha.WithReplicationSubscriber),
		"WithReplicationURL":             reflect.ValueOf(ha.WithReplicationURL),
		"WithRowIdentify":                reflect.ValueOf(ha.WithRowIdentify),
		"WithSnapshotInterval":           reflect.ValueOf(ha.WithSnapshotInterval),
		"WithStreamMaxAge":               reflect.ValueOf(ha.WithStreamMaxAge),
		"WithWaitFor":                    reflect.ValueOf(ha.WithWaitFor),

		// type definitions
		"AsyncNATSPublisher":   reflect.ValueOf((*ha.AsyncNATSPublisher)(nil)),
		"BackupFn":             reflect.ValueOf((*ha.BackupFn)(nil)),
		"CDCPublisher":         reflect.ValueOf((*ha.CDCPublisher)(nil)),
		"Change":               reflect.ValueOf((*ha.Change)(nil)),
		"ChangeSet":            reflect.ValueOf((*ha.ChangeSet)(nil)),
		"ChangeSetInterceptor": reflect.ValueOf((*ha.ChangeSetInterceptor)(nil)),
		"ChangeSetSerializer":  reflect.ValueOf((*ha.ChangeSetSerializer)(nil)),
		"ConnHooksConfig":      reflect.ValueOf((*ha.ConnHooksConfig)(nil)),
		"ConnHooksFactory":     reflect.ValueOf((*ha.ConnHooksFactory)(nil)),
		"ConnHooksProvider":    reflect.ValueOf((*ha.ConnHooksProvider)(nil)),
		"Connector":            reflect.ValueOf((*ha.Connector)(nil)),
		"DBSnapshotter":        reflect.ValueOf((*ha.DBSnapshotter)(nil)),
		"DebeziumData":         reflect.ValueOf((*ha.DebeziumData)(nil)),
		"DebeziumPayload":      reflect.ValueOf((*ha.DebeziumPayload)(nil)),
		"DebeziumSource":       reflect.ValueOf((*ha.DebeziumSource)(nil)),
		"DebeziumTransaction":  reflect.ValueOf((*ha.DebeziumTransaction)(nil)),
		"DynamicLeader":        reflect.ValueOf((*ha.DynamicLeader)(nil)),
		"EmbeddedNatsConfig":   reflect.ValueOf((*ha.EmbeddedNatsConfig)(nil)),
		"JSONPublisher":        reflect.ValueOf((*ha.JSONPublisher)(nil)),
		"LeaderProvider":       reflect.ValueOf((*ha.LeaderProvider)(nil)),
		"NATSPublisher":        reflect.ValueOf((*ha.NATSPublisher)(nil)),
		"NATSSnapshotter":      reflect.ValueOf((*ha.NATSSnapshotter)(nil)),
		"NATSSubscriber":       reflect.ValueOf((*ha.NATSSubscriber)(nil)),
		"NATSSubscriberConfig": reflect.ValueOf((*ha.NATSSubscriberConfig)(nil)),
		"NoopPublisher":        reflect.ValueOf((*ha.NoopPublisher)(nil)),
		"NoopSnapshotter":      reflect.ValueOf((*ha.NoopSnapshotter)(nil)),
		"NoopSubscriber":       reflect.ValueOf((*ha.NoopSubscriber)(nil)),
		"Option":               reflect.ValueOf((*ha.Option)(nil)),
		"Publisher":            reflect.ValueOf((*ha.Publisher)(nil)),
		"RowIdentify":          reflect.ValueOf((*ha.RowIdentify)(nil)),
		"SequenceProvider":     reflect.ValueOf((*ha.SequenceProvider)(nil)),
		"Statement":            reflect.ValueOf((*ha.Statement)(nil)),
		"StaticLeader":         reflect.ValueOf((*ha.StaticLeader)(nil)),
		"Subscriber":           reflect.ValueOf((*ha.Subscriber)(nil)),
		"TxSeqTracker":         reflect.ValueOf((*ha.TxSeqTracker)(nil)),
		"TxSeqTrackerProvider": reflect.ValueOf((*ha.TxSeqTrackerProvider)(nil)),
		"WriterPublisher":      reflect.ValueOf((*ha.WriterPublisher)(nil)),

		// interface wrapper definitions
		"_CDCPublisher":         reflect.ValueOf((*_github_com_litesql_go_ha_CDCPublisher)(nil)),
		"_ChangeSetInterceptor": reflect.ValueOf((*_github_com_litesql_go_ha_ChangeSetInterceptor)(nil)),
		"_ConnHooksProvider":    reflect.ValueOf((*_github_com_litesql_go_ha_ConnHooksProvider)(nil)),
		"_DBSnapshotter":        reflect.ValueOf((*_github_com_litesql_go_ha_DBSnapshotter)(nil)),
		"_LeaderProvider":       reflect.ValueOf((*_github_com_litesql_go_ha_LeaderProvider)(nil)),
		"_Publisher":            reflect.ValueOf((*_github_com_litesql_go_ha_Publisher)(nil)),
		"_SequenceProvider":     reflect.ValueOf((*_github_com_litesql_go_ha_SequenceProvider)(nil)),
		"_Subscriber":           reflect.ValueOf((*_github_com_litesql_go_ha_Subscriber)(nil)),
		"_TxSeqTracker":         reflect.ValueOf((*_github_com_litesql_go_ha_TxSeqTracker)(nil)),
	}
}

// _github_com_litesql_go_ha_CDCPublisher is an interface wrapper for CDCPublisher type
type _github_com_litesql_go_ha_CDCPublisher struct {
	IValue   interface{}
	WPublish func(data []ha.DebeziumData) error
}

func (W _github_com_litesql_go_ha_CDCPublisher) Publish(data []ha.DebeziumData) error {
	return W.WPublish(data)
}

// _github_com_litesql_go_ha_ChangeSetInterceptor is an interface wrapper for ChangeSetInterceptor type
type _github_com_litesql_go_ha_ChangeSetInterceptor struct {
	IValue       interface{}
	WAfterApply  func(a0 *ha.ChangeSet, a1 *sql.Conn, a2 error) error
	WBeforeApply func(a0 *ha.ChangeSet, a1 *sql.Conn) (skip bool, err error)
}

func (W _github_com_litesql_go_ha_ChangeSetInterceptor) AfterApply(a0 *ha.ChangeSet, a1 *sql.Conn, a2 error) error {
	return W.WAfterApply(a0, a1, a2)
}
func (W _github_com_litesql_go_ha_ChangeSetInterceptor) BeforeApply(a0 *ha.ChangeSet, a1 *sql.Conn) (skip bool, err error) {
	return W.WBeforeApply(a0, a1)
}

// _github_com_litesql_go_ha_ConnHooksProvider is an interface wrapper for ConnHooksProvider type
type _github_com_litesql_go_ha_ConnHooksProvider struct {
	IValue         interface{}
	WDisableHooks  func(a0 *sql.Conn) error
	WEnableHooks   func(a0 *sql.Conn) error
	WRegisterHooks func(a0 driver.Conn) (driver.Conn, error)
}

func (W _github_com_litesql_go_ha_ConnHooksProvider) DisableHooks(a0 *sql.Conn) error {
	return W.WDisableHooks(a0)
}
func (W _github_com_litesql_go_ha_ConnHooksProvider) EnableHooks(a0 *sql.Conn) error {
	return W.WEnableHooks(a0)
}
func (W _github_com_litesql_go_ha_ConnHooksProvider) RegisterHooks(a0 driver.Conn) (driver.Conn, error) {
	return W.WRegisterHooks(a0)
}

// _github_com_litesql_go_ha_DBSnapshotter is an interface wrapper for DBSnapshotter type
type _github_com_litesql_go_ha_DBSnapshotter struct {
	IValue          interface{}
	WLatestSnapshot func(ctx context.Context) (sequence uint64, reader io.ReadCloser, err error)
	WSetDB          func(a0 *sql.DB)
	WStart          func()
	WTakeSnapshot   func(ctx context.Context) (sequence uint64, err error)
}

func (W _github_com_litesql_go_ha_DBSnapshotter) LatestSnapshot(ctx context.Context) (sequence uint64, reader io.ReadCloser, err error) {
	return W.WLatestSnapshot(ctx)
}
func (W _github_com_litesql_go_ha_DBSnapshotter) SetDB(a0 *sql.DB) {
	W.WSetDB(a0)
}
func (W _github_com_litesql_go_ha_DBSnapshotter) Start() {
	W.WStart()
}
func (W _github_com_litesql_go_ha_DBSnapshotter) TakeSnapshot(ctx context.Context) (sequence uint64, err error) {
	return W.WTakeSnapshot(ctx)
}

// _github_com_litesql_go_ha_LeaderProvider is an interface wrapper for LeaderProvider type
type _github_com_litesql_go_ha_LeaderProvider struct {
	IValue          interface{}
	WIsLeader       func() bool
	WReady          func() chan struct{}
	WRedirectTarget func() string
}

func (W _github_com_litesql_go_ha_LeaderProvider) IsLeader() bool {
	return W.WIsLeader()
}
func (W _github_com_litesql_go_ha_LeaderProvider) Ready() chan struct{} {
	return W.WReady()
}
func (W _github_com_litesql_go_ha_LeaderProvider) RedirectTarget() string {
	return W.WRedirectTarget()
}

// _github_com_litesql_go_ha_Publisher is an interface wrapper for Publisher type
type _github_com_litesql_go_ha_Publisher struct {
	IValue    interface{}
	WPublish  func(cs *ha.ChangeSet) error
	WSequence func() uint64
}

func (W _github_com_litesql_go_ha_Publisher) Publish(cs *ha.ChangeSet) error {
	return W.WPublish(cs)
}
func (W _github_com_litesql_go_ha_Publisher) Sequence() uint64 {
	return W.WSequence()
}

// _github_com_litesql_go_ha_SequenceProvider is an interface wrapper for SequenceProvider type
type _github_com_litesql_go_ha_SequenceProvider struct {
	IValue     interface{}
	WLatestSeq func() uint64
}

func (W _github_com_litesql_go_ha_SequenceProvider) LatestSeq() uint64 {
	return W.WLatestSeq()
}

// _github_com_litesql_go_ha_Subscriber is an interface wrapper for Subscriber type
type _github_com_litesql_go_ha_Subscriber struct {
	IValue          interface{}
	WDeliveredInfo  func(ctx context.Context, name string) (any, error)
	WLatestSeq      func() uint64
	WRemoveConsumer func(ctx context.Context, name string) error
	WSetDB          func(a0 *sql.DB)
	WStart          func() error
}

func (W _github_com_litesql_go_ha_Subscriber) DeliveredInfo(ctx context.Context, name string) (any, error) {
	return W.WDeliveredInfo(ctx, name)
}
func (W _github_com_litesql_go_ha_Subscriber) LatestSeq() uint64 {
	return W.WLatestSeq()
}
func (W _github_com_litesql_go_ha_Subscriber) RemoveConsumer(ctx context.Context, name string) error {
	return W.WRemoveConsumer(ctx, name)
}
func (W _github_com_litesql_go_ha_Subscriber) SetDB(a0 *sql.DB) {
	W.WSetDB(a0)
}
func (W _github_com_litesql_go_ha_Subscriber) Start() error {
	return W.WStart()
}

// _github_com_litesql_go_ha_TxSeqTracker is an interface wrapper for TxSeqTracker type
type _github_com_litesql_go_ha_TxSeqTracker struct {
	IValue     interface{}
	WLatestSeq func() uint64
}

func (W _github_com_litesql_go_ha_TxSeqTracker) LatestSeq() uint64 {
	return W.WLatestSeq()
}
